# Generated by Django 3.2.9 on 2022-04-19 05:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_alias', models.CharField(max_length=30)),
                ('buyer_name', models.CharField(max_length=80)),
                ('company_name', models.CharField(max_length=80)),
                ('company_address', models.TextField(max_length=1000)),
                ('primary_phone_number', models.CharField(max_length=16)),
                ('secondary_phone_number', models.CharField(max_length=16)),
                ('email_id', models.CharField(max_length=100)),
                ('terms_and_conditions', models.TextField(max_length=500)),
                ('buyer_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 10, 58, 38, 302264))),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm', models.IntegerField()),
                ('bottom_gsm', models.FloatField()),
                ('paper_rate', models.FloatField()),
                ('scrape_rate', models.FloatField()),
                ('margin', models.FloatField()),
                ('cost_per_cup', models.FloatField()),
                ('cups_per_sku', models.IntegerField()),
                ('sku_per_mc', models.IntegerField()),
                ('print_cost', models.FloatField()),
                ('mc_cost', models.FloatField()),
                ('freight_per_container', models.FloatField()),
                ('mc_per_container', models.IntegerField()),
                ('dollor_rate', models.IntegerField()),
                ('add_cost_per_sku', models.FloatField()),
                ('mc_dollor_rate', models.FloatField()),
                ('sku_dollor_rate', models.FloatField()),
                ('mc_inr_rate', models.FloatField()),
                ('sku_inr_rate', models.FloatField()),
                ('product_name', models.CharField(max_length=30)),
                ('num_of_sku_per_container', models.IntegerField()),
                ('product_desription', models.TextField(max_length=20000)),
                ('item_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 10, 58, 38, 307776))),
            ],
        ),
        migrations.CreateModel(
            name='MasterCarton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('carton_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 10, 58, 38, 306782))),
            ],
        ),
        migrations.CreateModel(
            name='ProductDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('top_dia', models.FloatField()),
                ('bottom_dia', models.FloatField()),
                ('height', models.FloatField()),
                ('StackHeight', models.FloatField()),
                ('InCupHeight', models.FloatField()),
                ('Weight', models.FloatField()),
                ('product_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 10, 58, 38, 303306))),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 10, 58, 38, 309774))),
                ('buyer_alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.buyer')),
                ('items', models.ManyToManyField(blank=True, to='calculator.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCalculationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm', models.FloatField()),
                ('bottom_gsm', models.FloatField()),
                ('die_cup_sheet', models.FloatField()),
                ('num_of_blanks_per_sheet', models.IntegerField()),
                ('weight_blank_per_sheet', models.FloatField()),
                ('weight_bottom', models.FloatField()),
                ('over_head_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 10, 58, 38, 305775))),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.productdim')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='master_carton_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.mastercarton'),
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.productdim'),
        ),
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm', models.IntegerField(blank=True, null=True)),
                ('paper_rate', models.FloatField(blank=True, null=True)),
                ('scrape_rate', models.FloatField(blank=True, null=True)),
                ('margin', models.FloatField(blank=True, null=True)),
                ('cost_per_cup', models.FloatField(blank=True, null=True)),
                ('cups_per_sku', models.IntegerField(blank=True, null=True)),
                ('sku_per_mc', models.IntegerField(blank=True, null=True)),
                ('print_cost', models.FloatField(blank=True, null=True)),
                ('mc_cost', models.FloatField(blank=True, null=True)),
                ('freight_per_container', models.FloatField(blank=True, null=True)),
                ('mc_per_container', models.IntegerField(blank=True, null=True)),
                ('dollor_rate', models.FloatField(blank=True, null=True)),
                ('add_cost_per_sku', models.FloatField(blank=True, null=True)),
                ('rate_of_sku', models.FloatField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=30, null=True)),
                ('num_of_sku_per_container', models.IntegerField(blank=True, null=True)),
                ('product_desription', models.TextField(blank=True, max_length=20000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 10, 58, 38, 312798))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.productdim')),
            ],
        ),
    ]
